providers = [ "node" ]

[phases.setup]
# recent nixpkgs commit for latest bun
nixpkgsArchive = "d05592ea7e9656648093dfe0e817819486bd5054"

[phases.build]
cmds= [
	"cd diplomacy/web && bun install",
	"cd diplomacy/web && bun run --bun build"
]

[start]
cmd = "cd diplomacy/web && bunx serve build -l 3000"



