providers = [ "node" ]

[phases.setup]
nixPkgs = ["bun"]

[phases.build]
cmds= [
	"cd diplomacy/web && bun install",
	"cd diplomacy/web && bun run --bun build"
]

[start]
cmd = "cd diplomacy/web && bunx serve build -l 3000"



